### ISSUE TITLE
Ссылки на онлайн документацию нужно в README.md везде добавить

### ISSUE THREAD

**Issue by d1g** [nextgis/docs_formbuilder#2]
Github читатели не знают что документация в репозиториях(во всех) есть онлайн

http://docs.nextgis.ru/docs_formbuilder/source/toc.html, https://github.com/nextgis/docs_formbuilder
http://docs.nextgis.ru/docs_ngmobile/source/toc.html, https://github.com/nextgis/docs_ngmobile

**Comment by simgislab** [comment]
done
